/**:
  ros__parameters:
    callback_period: 0.05
    host: carla
    port: 2000
    id: dummy
    color: "168,0,27"
    spawn_point: 0
    x_offset: -30.0
    y_offset: 0.0
    create_markers: false
    generate_imu_pub: true
    generate_control_sub: true
    fix_y: true
    