adas_node:
  ros__parameters:
    local_velocity_topic: /carla/hero/local_velocity
    imu_topic: /carla/hero/imu
    control_topic: /carla/hero/vehicle_control_cmd
    tau: 2.0
    p: 10
    c: 10
    v_ref: 40.0
    u_limits: [-0.01, 1.0]
    phi_vals: [0.95, 0.95, 0.95]
    q_vals: [10., 1., 1.]
    s: 18.