/**:
  ros__parameters:
    tau: 2.0
    ts: 0.05
    p: 10
    c: 10
    v_ref: 78.0
    u_limits: [-0.4, 1.2]
    phi_vals: [0.4, 0.4, 0.4]
    q_vals: [4., 1., 1.]
    s: 18.
    p_term: 0.0
    i_term: 0.0
    d_term: 0.0
    i_min: -0.2
    i_max: 0.2
    i_trim_scale: 0.3
    i_trim_min: 0.1
    