services:
  ros2:
    build: .
    image: ros2_humble

    runtime: nvidia

    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    working_dir: /workspace
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../workspace:/workspace
      - ../data:/data

    networks:
      - carla_net

    tty: true
    stdin_open: true
    entrypoint: []

  carla:
    image: carlasim/carla:0.9.16

    runtime: nvidia

    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../import:/workspace/Import
      - ./entrypoint_carla.sh:/entrypoint_carla.sh

    networks:
      carla_net:
        aliases:
          - carla

    ports:
      - "2000-2002:2000-2002"

    shm_size: "8g"

    tty: true
    stdin_open: true
    entrypoint: ["bash", "/entrypoint_carla.sh"]

networks:
  carla_net:
    driver: bridge
